export const metadata: Metadata = {
  title: title: {
  default: "Prime Luz & Som | Eventos e Locações",
},,
  description: "Generated by Prime Luz & Som | Eventos e Locações",
  icons: {
    icon: "/favicon.png",
  },
};